export const TOKENS = {
	Db: Symbol.for("Db"),
	CategoryRepository: Symbol.for("CategoryRepository"),
	TransactionRepository: Symbol.for("TransactionRepository"),
	UserRepository: Symbol.for("UserRepository"),
	CreateCategoryUseCase: Symbol.for("CreateCategoryUseCase"),
	ListCategoriesUseCase: Symbol.for("ListCategoriesUseCase"),
	GetCategoryUseCase: Symbol.for("GetCategoryUseCase"),
	UpdateCategoryUseCase: Symbol.for("UpdateCategoryUseCase"),
	CreateTransactionUseCase: Symbol.for("CreateTransactionUseCase"),
	ListTransactionsUseCase: Symbol.for("ListTransactionsUseCase"),
	UpdateTransactionUseCase: Symbol.for("UpdateTransactionUseCase"),
	DeleteTransactionUseCase: Symbol.for("DeleteTransactionUseCase"),
	RegisterUserUseCase: Symbol.for("RegisterUserUseCase"),
	LoginUserUseCase: Symbol.for("LoginUserUseCase"),
	CreateJwtService: Symbol.for("CreateJwtService"),
	CreateJwtTokenProvider: Symbol.for("CreateJwtTokenProvider"),
} as const;
